### ISSUE TITLE
Static dir needs revised commit msg

### ISSUE THREAD

**Issue by amsheppard** [iguananaut/ysng#1]
A congregation approached a scientist.
"We believe in {Gawd, Feminism, Nonbinary genders, Otherkin}!"
"That's all well and good" said the physicist "... but where's your control?"

Vive la révolution.

#KeepYourPoliticsOutOfSTEMYaSnowflake

**Comment by iguananaut** [comment]
lol, what?

**Comment by amsheppard** [comment]
< _sigh_ > There are 10 types of people in this world; _those that get it..._

**Comment by iguananaut** [comment]
I think I get it?  Is the joke that you don't know how to tell a joke?

**Comment by amsheppard** [comment]
Yep; that's it, _exactly._  Here's another one for 'ya:
There are two types of people in this world: _those that can extrapolate from incomplete data..._

Toodles, TransTrender.

**Comment by iguananaut** [comment]
You're not any levels of irony my dude, you're just incoherent and mad that I, a feminist, am actually funny 😬
